/*
 * Copyright (c) 2024 Nordic Semiconductor
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/kernel.h>

/*
 * start of auto generated code based on the contents of the .zms file.
 *
 * The output does not need to be DT like headers/macros like it is here, it
 * could be any machine parsable format. But obviously if this shall replace
 * software properties which are currently in the devicetree, better make
 * something similar.
 */

#define ZML_P_foo0_bar 1.8F
#define ZML_P_foo0_zar "big"
#define ZML_P_foo1_bar 0.5F
#define ZML_F_foo(fn) fn(foo0) fn(foo1)
#define ZML_FS_foo(fn, sep) fn(foo0) __DEBRACKET sep fn(foo1)

/*
 * end of autogenerated code
 */

#define ZML_FOREACH_SCHEMA_INST(schema, fn) \
	_CONCAT(ZML_F_, schema)(fn)

#define ZML_FOREACH_SCHEMA_INST_SEP(schema, fn, sep) \
	_CONCAT(ZML_FS_, schema)(fn, sep)

#define ZML_PROP(label, prop) \
	_CONCAT_4(ZML_P_, label, _, prop)

#define FOO_BAR_STR(label) \
	STRINGIFY(ZML_PROP(label, bar))

static const char *foos[] = {
	ZML_FOREACH_SCHEMA_INST_SEP(foo, FOO_BAR_STR, (,))
};

int main(void)
{
	for (size_t i = 0; i < ARRAY_SIZE(foos); i++) {
		printk("foo: %s \n", foos[i]);
	}

	return 0;
}
